# Generated by Django 6.0.2 on 2026-04-20 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GescanntesDokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('datei', models.FileField(upload_to='scans/')),
                ('erkannter_text', models.TextField(blank=True, null=True)),
                ('verarbeitet', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Benutzerprofil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefon', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('rechnungsnummer', models.CharField(max_length=50, unique=True)),
                ('datum', models.DateField()),
                ('faelligkeitsdatum', models.DateField()),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('bezahlt', 'Bezahlt'), ('ueberfaellig', 'Überfällig')], default='offen', max_length=20)),
                ('kontakt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kontakt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mahnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('mahnstufe', models.PositiveIntegerField()),
                ('datum', models.DateField()),
                ('gebuehr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gesendet', models.BooleanField(default=False)),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahnungen', to='api.rechnung')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rechnungsdokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('datei', models.FileField(upload_to='rechnungen/')),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='api.rechnung')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rechnungsposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('beschreibung', models.CharField(max_length=255)),
                ('menge', models.PositiveIntegerField()),
                ('preis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='api.rechnung')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zahlung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum', models.DateField()),
                ('methode', models.CharField(choices=[('bank', 'Bank'), ('paypal', 'PayPal'), ('cash', 'Bar')], max_length=20)),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zahlungen', to='api.rechnung')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
