# Generated by Django 6.0.3 on 2026-04-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(max_length=50)),
                ('adresse', models.TextField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
