# Generated by Django 6.0.3 on 2026-04-03 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechnungsnummer', models.CharField(max_length=50, unique=True)),
                ('datum', models.DateField()),
                ('faelligkeitsdatum', models.DateField()),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('bezahlt', 'Bezahlt'), ('ueberfaellig', 'Überfällig')], default='offen', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kunden')),
            ],
        ),
    ]
