# Generated by Django 6.0.3 on 2026-04-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rechnung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rechnungsposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(max_length=255)),
                ('menge', models.PositiveIntegerField()),
                ('preis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='api.rechnung')),
            ],
        ),
    ]
