# Generated by Django 6.0.3 on 2026-04-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rechnungsposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='scans/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='betrag',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.rechnung')),
            ],
        ),
        migrations.CreateModel(
            name='Mahnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahnstufe', models.PositiveIntegerField()),
                ('datum', models.DateField()),
                ('gebuehr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gesendet', models.BooleanField(default=False)),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahnungen', to='api.rechnung')),
            ],
        ),
        migrations.CreateModel(
            name='Zahlung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum', models.DateField()),
                ('methode', models.CharField(choices=[('bank', 'Bank'), ('paypal', 'PayPal'), ('cash', 'Cash')], max_length=20)),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zahlungen', to='api.rechnung')),
            ],
        ),
    ]
